all:
	../bin/trace2model.py 
	../bin/filterposixonly.py
	../bin/filteraddcomputeevents.py
	PYTHONPATH=\${PWD}/../tmpl:\${PYTHONPATH} skel template ../tmpl/CMakeLists_txt.tmpl --model ../model/grey-scott-posix-compute.json:posix-model,../model/tweak.json:tweak --outfile ../repos/grey-scott/CMakeLists.txt
	PYTHONPATH=\${PWD}/../tmpl:\${PYTHONPATH} skel template ../tmpl/main_src_cxx.tmpl --model ../model/grey-scott-posix-compute.json:posix-model,../model/tweak.json:tweak --outfile ../repos/grey-scott/skel_${self.models['posix-model']['name']}.cxx
	PYTHONPATH=\${PWD}/../tmpl:\${PYTHONPATH} skel template ../tmpl/create_synthetic_data_cxx.tmpl --model ../model/grey-scott-posix-compute.json:posix-model,../model/tweak.json:tweak --outfile ../repos/grey-scott/create_synthetic_data.cxx
#for $t_rank in range($self.models['posix-model']['num_ranks'])
	PYTHONPATH=\${PWD}/../tmpl:\${PYTHONPATH} skel template ../tmpl/rank_src_cxx.tmpl --arg rank:$t_rank --model ../model/grey-scott-posix-compute.json:posix-model,../model/tweak.json:tweak --outfile ../repos/grey-scott/rank<%='{0:05d}'.format(t_rank)%>.cxx
#end for
	mkdir -p ../repos/grey-scott/build
	cd ../repos/grey-scott/build && cmake .. && make && cd -

refresh:
	skel template ../tmpl/Makefile.tmpl --model ../model/grey-scott-posix-compute.json:posix-model,../model/tweak.json:tweak --outfile Makefile



create_synthetic:
	cd ../repos/grey-scott/build && ./create_synthetic_data && cd -

run:
	cd ../repos/grey-scott/build && mpirun -np 36 -oversubscribe ./skel_grey_scott_posix_compute && cd -
	cd ../repos/grey-scott/build && ~/sw/skel-io/bin/skel-io-merge && cd -

run-tau:
	cd ../repos/grey-scott/build && mpirun -np 36 -oversubscribe tau_exec -T mpi,pthread -io -skel ./skel_grey_scott_posix_compute && cd -

.PHONY: create_synthetic run run-tau


